from __future__ import annotations

import hashlib
import json

from .schemas import CompiledAnalysis, canonical_model_json_bytes
from .validator import ValidatedAnalysisSpec

COMPILER_VERSION = "analysis-spec-compiler-v1"
RUNTIME_POLICY_ID = "dataset-analysis-spec-v1"
EXPECTED_OUTPUTS = [
    "analysis-spec.json",
    "results.json",
    "summary.csv",
    "executed.ipynb",
    "execution.log",
    "environment.json",
]


def compile_analysis_spec(
    validated: ValidatedAnalysisSpec,
    *,
    compiler_version: str = COMPILER_VERSION,
) -> CompiledAnalysis:
    """Compile a validated spec into deterministic, policy-verifiable Python."""

    if compiler_version != COMPILER_VERSION:
        raise ValueError(f"unsupported compiler version: {compiler_version}")
    spec_json = canonical_model_json_bytes(validated.spec).decode("utf-8")
    spec_sha256 = hashlib.sha256(spec_json.encode("utf-8")).hexdigest()
    bindings = json.dumps(
        {
            "datasetDelimiter": validated.dataset_delimiter,
            "datasetEncoding": validated.dataset_encoding,
            "methodSelectionReason": validated.method_selection_reason,
            "resolvedMethod": validated.resolved_method,
        },
        allow_nan=False,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    operation_type = validated.spec.operation.type
    body = {
        "descriptive": _descriptive_body,
        "two-group-comparison": _two_group_body,
        "correlation": _correlation_body,
    }[operation_type]()
    code = "\n".join(
        (
            "import json",
            "import math",
            "import matplotlib",
            "matplotlib.use('Agg')",
            "import matplotlib.pyplot as plt",
            "import numpy as np",
            "import pandas as pd",
            "from scipy import stats",
            "",
            f"SPEC_JSON = {spec_json!r}",
            f"COMPILER_BINDINGS_JSON = {bindings!r}",
            "spec = json.loads(SPEC_JSON)",
            "compiler_bindings = json.loads(COMPILER_BINDINGS_JSON)",
            "operation = spec['operation']",
            "missing_values = frozenset(('', 'na', 'n/a', 'nan', 'none', 'null'))",
            "data = pd.read_csv(DATASET_PATH, sep=compiler_bindings['datasetDelimiter'], encoding=compiler_bindings['datasetEncoding'], dtype='string', keep_default_na=False)",
            "for column_name in data.columns:",
            "    normalized_missing = data[column_name].str.strip().str.casefold().isin(missing_values)",
            "    data[column_name] = data[column_name].mask(normalized_missing)",
            "rng = np.random.default_rng(spec['randomSeed'])",
            "",
            *_common_helpers(),
            *body,
            "",
            "with (RUN_DIR / 'analysis-spec.json').open('w', encoding='utf-8') as stream:",
            "    json.dump(spec, stream, allow_nan=False, ensure_ascii=False, sort_keys=True, separators=(',', ':'))",
            "with (RUN_DIR / 'results.json').open('w', encoding='utf-8') as stream:",
            "    json.dump(structured_result, stream, allow_nan=False, ensure_ascii=False, sort_keys=True, separators=(',', ':'))",
            "summary.to_csv(RUN_DIR / 'summary.csv', index=False)",
            "print(json.dumps(structured_result, allow_nan=False, ensure_ascii=False, sort_keys=True))",
        )
    )
    expected_outputs = list(EXPECTED_OUTPUTS)
    if validated.spec.operation.plot != "none":
        expected_outputs.append("figure.png")
    return CompiledAnalysis(
        compiler_version=compiler_version,
        spec_sha256=spec_sha256,
        code=code,
        code_sha256=hashlib.sha256(code.encode("utf-8")).hexdigest(),
        expected_outputs=expected_outputs,
        runtime_policy_id=RUNTIME_POLICY_ID,
    )


def _common_helpers() -> tuple[str, ...]:
    return (
        "def finite_number(value):",
        "    number = float(value)",
        "    if not math.isfinite(number):",
        "        raise ValueError('analysis produced a non-finite value')",
        "    return number",
        "",
        "def safe_csv_value(value):",
        "    if not isinstance(value, str):",
        "        return value",
        "    cleaned = ''.join(character if character.isprintable() else ' ' for character in value)",
        "    if cleaned.lstrip().startswith(('=', '+', '-', '@')):",
        "        return \"'\" + cleaned",
        "    return cleaned",
        "",
        "def save_figure(figure):",
        "    figure.tight_layout()",
        "    figure.savefig(RUN_DIR / 'figure.png', dpi=150)",
        "    plt.close(figure)",
        "",
    )


def _result_envelope(operation_result: str, *, requested_method: str) -> tuple[str, ...]:
    return (
        "structured_result = {",
        "    'schemaVersion': '1',",
        "    'objective': spec['objective'],",
        "    'operationType': operation['type'],",
        "    'datasetSourceId': spec['datasetSourceId'],",
        "    'datasetContentHash': spec['datasetContentHash'],",
        "    'datasetProfileHash': spec['datasetProfileHash'],",
        f"    'requestedMethod': {requested_method},",
        "    'resolvedMethod': compiler_bindings['resolvedMethod'],",
        "    'methodSelectionReason': compiler_bindings['methodSelectionReason'],",
        "    'sampleSummary': sample_summary,",
        f"    'result': {operation_result},",
        "    'warnings': warnings,",
        "    'limitations': spec['limitations'],",
        "}",
    )


def _descriptive_body() -> tuple[str, ...]:
    return (
        "statistics_rows = []",
        "result_columns = []",
        "selected_frame = data.loc[:, operation['columns']]",
        "missing_rows = int(selected_frame.isna().any(axis=1).sum())",
        "for column_name in operation['columns']:",
        "    series = data.loc[:, column_name]",
        "    missing_count = int(series.isna().sum())",
        "    values = {}",
        "    for statistic in operation['statistics']:",
        "        non_missing = series.dropna()",
        "        if statistic == 'count':",
        "            value = int(non_missing.shape[0])",
        "        elif statistic == 'missing':",
        "            value = missing_count",
        "        elif statistic == 'unique':",
        "            value = int(non_missing.nunique())",
        "        elif statistic == 'frequency':",
        "            counts = non_missing.astype('string').value_counts().head(20)",
        "            value = '; '.join(f'{safe_csv_value(str(key))}:{int(count)}' for key, count in counts.items())",
        "        else:",
        "            numeric = pd.to_numeric(non_missing, errors='raise')",
        "            if statistic == 'mean':",
        "                value = finite_number(numeric.mean())",
        "            elif statistic == 'std':",
        "                value = finite_number(numeric.std(ddof=1))",
        "            elif statistic == 'median':",
        "                value = finite_number(numeric.median())",
        "            elif statistic == 'min':",
        "                value = finite_number(numeric.min())",
        "            elif statistic == 'max':",
        "                value = finite_number(numeric.max())",
        "            elif statistic == 'q1':",
        "                value = finite_number(numeric.quantile(0.25))",
        "            elif statistic == 'q3':",
        "                value = finite_number(numeric.quantile(0.75))",
        "            elif statistic == 'iqr':",
        "                value = finite_number(numeric.quantile(0.75) - numeric.quantile(0.25))",
        "            else:",
        "                raise ValueError('unsupported descriptive statistic')",
        "        values[statistic] = value",
        "        statistics_rows.append({'column': safe_csv_value(column_name), 'statistic': statistic, 'value': value})",
        "    result_columns.append({'column': column_name, 'sampleSize': int(non_missing.shape[0]), 'missingCount': missing_count, 'statistics': values})",
        "if operation['plot'] != 'none':",
        "    figure, axes = plt.subplots(len(operation['columns']), 1, figsize=(8, 5 * len(operation['columns'])), squeeze=False)",
        "    for index, column_name in enumerate(operation['columns']):",
        "        series = data.loc[:, column_name].dropna()",
        "        axis = axes[index][0]",
        "        if operation['plot'] == 'histogram':",
        "            pd.to_numeric(series, errors='raise').plot(kind='hist', bins=20, ax=axis)",
        "        else:",
        "            series.astype('string').value_counts().head(20).plot(kind='bar', ax=axis)",
        "        axis.set_title(f'Distribution: {column_name}')",
        "    save_figure(figure)",
        "summary = pd.DataFrame(statistics_rows)",
        "sample_summary = {'totalRows': int(data.shape[0]), 'analyzedRows': int(data.shape[0] - missing_rows), 'missingRows': int(missing_rows)}",
        "warnings = []",
        "operation_result = {'type': 'descriptive', 'columns': result_columns}",
        *_result_envelope("operation_result", requested_method="'descriptive'"),
    )


def _two_group_body() -> tuple[str, ...]:
    return (
        "outcome_column = operation['outcomeColumn']",
        "group_column = operation['groupColumn']",
        "group_names = operation['groups']",
        "frame = data.loc[:, [group_column, outcome_column]].copy()",
        "frame[group_column] = frame[group_column].str.strip()",
        "frame[outcome_column] = pd.to_numeric(frame[outcome_column], errors='coerce')",
        "group_values = {}",
        "sample_sizes = {}",
        "missing_counts = {}",
        "descriptive = {}",
        "for group_name in group_names:",
        "    selected = frame.loc[frame[group_column].astype('string') == str(group_name), outcome_column]",
        "    missing_counts[group_name] = int(selected.isna().sum())",
        "    clean = selected.dropna().to_numpy(dtype=float)",
        "    if clean.shape[0] < 3:",
        "        raise ValueError('each comparison group requires at least three observations')",
        "    group_values[group_name] = clean",
        "    sample_sizes[group_name] = int(clean.shape[0])",
        "    descriptive[group_name] = {'mean': finite_number(np.mean(clean)), 'std': finite_number(np.std(clean, ddof=1)), 'median': finite_number(np.median(clean))}",
        "first = group_values[group_names[0]]",
        "second = group_values[group_names[1]]",
        "resolved_method = compiler_bindings['resolvedMethod']",
        "confidence_level = spec['confidenceLevel']",
        "alpha = 1.0 - confidence_level",
        "warnings = []",
        "if resolved_method == 'welch-t-test':",
        "    test = stats.ttest_ind(first, second, equal_var=False)",
        "    pooled_variance = (((first.size - 1) * np.var(first, ddof=1)) + ((second.size - 1) * np.var(second, ddof=1))) / (first.size + second.size - 2)",
        "    pooled_sd = math.sqrt(float(pooled_variance))",
        "    raw_d = (float(np.mean(first)) - float(np.mean(second))) / pooled_sd",
        "    correction = 1.0 - 3.0 / (4.0 * (first.size + second.size) - 9.0)",
        "    effect_size = finite_number(raw_d * correction)",
        "    effect_name = 'hedges-g'",
        "    effect_se = math.sqrt((first.size + second.size) / (first.size * second.size) + (effect_size * effect_size) / (2.0 * (first.size + second.size - 2)))",
        "    critical = finite_number(stats.norm.ppf(1.0 - alpha / 2.0))",
        "    confidence_interval = [finite_number(effect_size - critical * effect_se), finite_number(effect_size + critical * effect_se)]",
        "else:",
        "    test = stats.mannwhitneyu(first, second, alternative='two-sided', method='auto')",
        "    effect_size = finite_number(2.0 * float(test.statistic) / (first.size * second.size) - 1.0)",
        "    effect_name = 'rank-biserial'",
        "    bootstrap = []",
        "    for _ in range(1000):",
        "        left = rng.choice(first, size=first.size, replace=True)",
        "        right = rng.choice(second, size=second.size, replace=True)",
        "        statistic = stats.mannwhitneyu(left, right, alternative='two-sided', method='auto').statistic",
        "        bootstrap.append(2.0 * float(statistic) / (left.size * right.size) - 1.0)",
        "    confidence_interval = [finite_number(np.quantile(bootstrap, alpha / 2.0)), finite_number(np.quantile(bootstrap, 1.0 - alpha / 2.0))]",
        "if operation['checkAssumptions']:",
        "    for group_name, values in group_values.items():",
        "        checked = values[:5000]",
        "        if checked.size >= 3 and checked.size <= 5000 and stats.shapiro(checked).pvalue < 0.05:",
        "            warnings.append(f'Profile-independent Shapiro-Wilk diagnostic indicates non-normality in group {group_name}.')",
        "operation_result = {'type': 'two-group-comparison', 'groupColumn': group_column, 'outcomeColumn': outcome_column, 'groups': group_names, 'sampleSizes': sample_sizes, 'missingCounts': missing_counts, 'descriptiveStatistics': descriptive, 'testStatistic': finite_number(test.statistic), 'pValue': finite_number(test.pvalue), 'effectSizeName': effect_name, 'effectSize': effect_size, 'confidenceInterval': confidence_interval}",
        "summary = pd.DataFrame([{'group': safe_csv_value(name), 'sampleSize': sample_sizes[name], 'missingCount': missing_counts[name], **descriptive[name]} for name in group_names])",
        "if operation['plot'] != 'none':",
        "    figure, axis = plt.subplots(figsize=(8, 5))",
        "    if operation['plot'] == 'violin':",
        "        axis.violinplot([first, second], showmeans=True, showmedians=True)",
        "        axis.set_xticks([1, 2], [safe_csv_value(name) for name in group_names])",
        "    else:",
        "        axis.boxplot([first, second], tick_labels=[safe_csv_value(name) for name in group_names])",
        "    axis.set_title(f'{outcome_column} by {group_column}')",
        "    axis.set_ylabel(outcome_column)",
        "    save_figure(figure)",
        "selected_group_mask = frame[group_column].isin(group_names)",
        "group_missing_rows = int(frame[group_column].isna().sum())",
        "missing_rows = int(sum(missing_counts.values()) + group_missing_rows)",
        "analyzed_rows = int(sum(sample_sizes.values()))",
        "sample_summary = {'totalRows': int(frame.shape[0]), 'analyzedRows': analyzed_rows, 'missingRows': missing_rows}",
        "excluded_rows = int((~selected_group_mask & frame[group_column].notna()).sum())",
        "if excluded_rows:",
        "    warnings.append(f'{excluded_rows} row(s) were excluded because their group value was not selected.')",
        "if operation['method'] == 'auto':",
        "    warnings.append('The v1 automatic method rule is not a complete distributional diagnostic.')",
        *_result_envelope("operation_result", requested_method="operation['method']"),
    )


def _correlation_body() -> tuple[str, ...]:
    return (
        "x_column = operation['xColumn']",
        "y_column = operation['yColumn']",
        "frame = data.loc[:, [x_column, y_column]].apply(pd.to_numeric, errors='coerce')",
        "complete = frame.dropna()",
        "if complete.shape[0] < 3:",
        "    raise ValueError('correlation requires at least three complete pairs')",
        "x_values = complete[x_column].to_numpy(dtype=float)",
        "y_values = complete[y_column].to_numpy(dtype=float)",
        "resolved_method = compiler_bindings['resolvedMethod']",
        "if resolved_method == 'pearson':",
        "    test = stats.pearsonr(x_values, y_values)",
        "else:",
        "    test = stats.spearmanr(x_values, y_values)",
        "correlation = finite_number(test.statistic)",
        "confidence_interval = None",
        "warnings = ['Correlation does not establish causation.']",
        "if operation['confidenceInterval']:",
        "    confidence_level = spec['confidenceLevel']",
        "    alpha = 1.0 - confidence_level",
        "    if resolved_method == 'pearson' and complete.shape[0] > 3 and abs(correlation) < 1.0:",
        "        transformed = np.arctanh(correlation)",
        "        margin = stats.norm.ppf(1.0 - alpha / 2.0) / math.sqrt(complete.shape[0] - 3)",
        "        confidence_interval = [finite_number(np.tanh(transformed - margin)), finite_number(np.tanh(transformed + margin))]",
        "    elif resolved_method == 'pearson' and abs(correlation) == 1.0:",
        "        confidence_interval = [correlation, correlation]",
        "        warnings.append('The Pearson confidence interval is degenerate because the observed correlation is perfect.')",
        "    else:",
        "        bootstrap = []",
        "        for _ in range(1000):",
        "            indexes = rng.integers(0, complete.shape[0], size=complete.shape[0])",
        "            if resolved_method == 'pearson':",
        "                candidate = stats.pearsonr(x_values[indexes], y_values[indexes]).statistic",
        "            else:",
        "                candidate = stats.spearmanr(x_values[indexes], y_values[indexes]).statistic",
        "            if math.isfinite(float(candidate)):",
        "                bootstrap.append(float(candidate))",
        "        if not bootstrap:",
        "            raise ValueError('correlation confidence interval could not be estimated')",
        "        confidence_interval = [finite_number(np.quantile(bootstrap, alpha / 2.0)), finite_number(np.quantile(bootstrap, 1.0 - alpha / 2.0))]",
        "missing_pairs = int(frame.shape[0] - complete.shape[0])",
        "operation_result = {'type': 'correlation', 'xColumn': x_column, 'yColumn': y_column, 'sampleSize': int(complete.shape[0]), 'missingPairs': missing_pairs, 'correlation': correlation, 'pValue': finite_number(test.pvalue), 'confidenceInterval': confidence_interval}",
        "summary = pd.DataFrame([{'xColumn': safe_csv_value(x_column), 'yColumn': safe_csv_value(y_column), 'sampleSize': int(complete.shape[0]), 'missingPairs': missing_pairs, 'method': resolved_method, 'correlation': correlation, 'pValue': finite_number(test.pvalue), 'confidenceIntervalLower': confidence_interval[0] if confidence_interval else None, 'confidenceIntervalUpper': confidence_interval[1] if confidence_interval else None}])",
        "if operation['plot'] == 'scatter':",
        "    figure, axis = plt.subplots(figsize=(8, 5))",
        "    axis.scatter(x_values, y_values, alpha=0.75)",
        "    axis.set_xlabel(x_column)",
        "    axis.set_ylabel(y_column)",
        "    axis.set_title(f'{y_column} versus {x_column}')",
        "    save_figure(figure)",
        "sample_summary = {'totalRows': int(frame.shape[0]), 'analyzedRows': int(complete.shape[0]), 'missingRows': missing_pairs}",
        *_result_envelope("operation_result", requested_method="operation['method']"),
    )
